apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: docker.io/library/spfinance:latest
        imagePullPolicy: Never
        command: ["python"]
        args: ["SPFinance/scraper/run.py", "--plugin-name offline.offlineScraper", "--configuration-getter-name file_configuration_getter", "--db-host localhost", "--objects-to-scrap AAPL NVDA", "--start-datetime 2023.12.02T19:22:22", "--end-datetime 2024.01.01T12:38:22"]
        ports:
        - containerPort: 80