version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=finance

  backend:
    image: spbackend
    volumes:
      - ./src/:/app/mounted
    ports:
      - 5000:5000
    command: sh -c "cd /app/mounted && uvicorn SPFinance.database_connection.main:app --reload --host 0.0.0.0 --port 5000"

  frontend:
    build: ./src/frontend
    volumes:
      - './src/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true


networks:
  default:
    driver: bridge