CREATE TABLE STOCK (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10),
    observed_at TIMESTAMPTZ,
    observed_at_utc TIMESTAMP,
    interval INT,
    open_price FLOAT,
    high_price FLOAT,
    low_price FLOAT,
    close_price FLOAT,
    adj_close FLOAT,
    volume FLOAT
);
CREATE INDEX STOCK_SYMBOL_INDEX
ON STOCK USING HASH (symbol);