CREATE TABLE STOCK (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10),
    observed_at TIMESTAMPTZ,
    observed_at_utc TIMESTAMP,
    price FLOAT,
    interval INTERVAL,
    max_price FLOAT,
    min_price FLOAT
);