CREATE TABLE STOCK (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10),
    observed_at TIMESTAMPTZ,
    observed_at_utc TIMESTAMP,
    interval INT,
    open_price FLOAT,
    high_price FLOAT,
    low_price FLOAT,
    close_price FLOAT,
    adj_close FLOAT,
    volume FLOAT
);
CREATE INDEX STOCK_SYMBOL_INDEX
ON STOCK USING HASH (symbol);

CREATE TABLE PREDICTION (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10),
    model_id VARCHAR(16),
    prediction_time_utc TIMESTAMP,
    observed_at TIMESTAMPTZ,
    observed_at_utc TIMESTAMP,
    interval INT,
    predictions FLOAT[],
);
CREATE INDEX PREDICTION_SYMBOL_INDEX
ON PREDICTION USING HASH (symbol);